### ISSUE TITLE
Multidimensional biases

### ISSUE THREAD

**Issue by jfloresc** [xqding/FastMBAR#1]
Hi! 

Really great method and code, I wonder if it is possible to estimate free energy PMF profiles using multiple biases, for example two or three reaction coordinates.

Best regards,
Jose

**Comment by xqding** [comment]
Hi Jose,
Thanks for your interest in the work.
Yes. It can. I am writing a tutorial on how to use it to compute the 2d PMF profile for the dialanine. It is almost ready. I will push it onto the example page of the documentation (https://fastmbar.readthedocs.io) very soon. I will let you now when it is done.

**Comment by jfloresc** [comment]
Thanks a lot Xinqiang, I figure out a bit better of what I want. Remove the effects of angular restraints over an umbrella sampling calculations. I could use the following equation:

[img]http://www.sciweavers.org/tex2img.php?eq=p_%7Bi%7D%20%28r%29%20%3D%20%20%5Cint%20p_%7Bi%7D%20%28r%2C%20%5Ctheta%20%2C%20%5Cphi%20%29%20%20e%5E%7BU%28%20%5Ctheta%20-%20%5Ctheta%20_%7Bo%7D%29%7D%20e%5E%7BU%28%20%5Cphi%20-%5Cphi%20_%7Bo%7D%29%7D%20%20%20d%20%5Ctheta%20d%20%20%20%5Cphi%20%20&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0[/img]

Would it be possible to implement it in your script? 

Thanks!

**Comment by xqding** [comment]
Hope you have solved your problem. 
Here is an example showing how to compute two dimensional PMF of dialanine dihedrals. (https://fastmbar.readthedocs.io/en/latest/dialanine_PMF.html) You might be able to adapt it to your case.

**Comment by jfloresc** [comment]
Thanks a lot! I have taken a look at both examples, but there is something that doesn't work for my case yet. I have got the MBAR object for my set of umbrella simulations and got a free energy profile that looks reasonable. See below:
 
![PMF_fast_mbar_0](https://user-images.githubusercontent.com/30071862/73127583-c2a4b180-3fc2-11ea-8134-dc29766c6ab5.png)

For calculating the PMF , I have used the following:

`L = 30 
dis = np.concatenate(distances)
d_min = 2.8 # np.min(distances)
d_max = 5.0 # np.max(distances)

# generate centers
d_PMF = np.linspace(d_min, d_max, L, endpoint = False)
B = np.zeros((L, N))

# resample
for i in range(L):
    br = bias(dis, K, d_PMF[i] ) * beta
    B[i, :] = br

## compute PMF using the energy matrix B
PMF, _ = fastmbar.calculate_free_energies_of_perturbed_states(B)
`
But I get the following:
![PMF_fast_mbar](https://user-images.githubusercontent.com/30071862/73127638-a5241780-3fc3-11ea-9a6e-ff98737564c1.png)
The bias(dis, K, d_PMF[i] ) function is used to generate the A function and is an standard harmonic potential:

`def bias(d, K, d0):
    # d: reaction coordinate array
    # K: force constant
    # d0: equilibrium value array
    return 0.5 * K * (d-d0)**2.`

I have also used the same perturbated biasing function with 0 or infinite values from your examples. The following code and corresponding plot are below:

`L=24
dis = np.concatenate(distances)
d_min = 2.8 # np.min(distances)
d_max = 5.0 # np.max(distances)
d_PMF = np.linspace(d_min, d_max, L, endpoint = False)
B = np.zeros((L, N))
width = (np.abs(d_max) - np.abs(d_min)) / L
B = np.zeros((L, N), np.float64)
# resample
for i in range(L):
    d_center = d_PMF[i]
    d_low = d_center - 0.5*width
    d_high = d_center + 0.5*width
    indicator = ((dis > d_low) & (dis <= d_high)) 
    B[i, ~indicator] = np.inf
`
![PMF_fast_mbar](https://user-images.githubusercontent.com/30071862/73127711-e10bac80-3fc4-11ea-8661-7387c5278c71.png)

The first attempt of calculating the PMF seems more intuitive to me, but I still don't grasp the meaning of a 0 or infinite biasing potential.

Thanks!

**Comment by xqding** [comment]
I am not quite clear about how you set up your umbrella sampling and which PMF you are trying to compute. The following is my guess based on your current description.

You are trying to compute PMF along r. In umbrella sampling, the restraint potentials are applied on \theta and \phi in each window. If this is the case, you can generate the matrix A as in the example and you don't have to remove the contribution of the orientational restraints. Then you can compute PMF along r by computing the matrix B as you did here.
